In [3]:
import httpx 
import requests 
import yfinance as yf
import pandas as pd 
from datetime import datetime, timedelta

In [5]:
spx = yf.Ticker("^GSPC")
spx_hist = spx.history(start="2025-01-28", end="2025-03-31", interval="1d")

In [7]:
spx_hist = spx_hist[["Open", "Close", "High", "Low", "Volume"]].reset_index()
spx_hist.rename(columns={"Date": "date"}, inplace=True)

In [9]:
spx_hist.to_csv("/Users/kennethzhang/Desktop/VolAuction/data/spx_spot_daily.csv", index=False)

In [15]:
import time

start_date = datetime.strptime("2025-01-28", "%Y-%m-%d")
end_date = datetime.strptime("2025-03-31", "%Y-%m-%d")

all_data = []

current = start_date
while current <= end_date:
    print(f"Fetching {current.date()}...")
    es = yf.Ticker("ES=F")

    try:
        hist = es.history(period="7d", interval="1m")
        filtered = hist[hist.index.date == current.date()]
        filtered = filtered.copy()
        filtered["date"] = current.date()
        all_data.append(filtered)
    except Exception as e:
        print(f"Error on {current.date()}: {e}")
    
    current += timedelta(days=1)
    time.sleep(1)

Fetching 2025-01-28...
Fetching 2025-01-29...
Fetching 2025-01-30...
Fetching 2025-01-31...
Fetching 2025-02-01...
Fetching 2025-02-02...
Fetching 2025-02-03...
Fetching 2025-02-04...
Fetching 2025-02-05...
Fetching 2025-02-06...
Fetching 2025-02-07...
Fetching 2025-02-08...
Fetching 2025-02-09...
Fetching 2025-02-10...
Fetching 2025-02-11...
Fetching 2025-02-12...
Fetching 2025-02-13...
Fetching 2025-02-14...
Fetching 2025-02-15...
Fetching 2025-02-16...
Fetching 2025-02-17...
Fetching 2025-02-18...
Fetching 2025-02-19...
Fetching 2025-02-20...
Fetching 2025-02-21...
Fetching 2025-02-22...
Fetching 2025-02-23...
Fetching 2025-02-24...
Fetching 2025-02-25...
Fetching 2025-02-26...
Fetching 2025-02-27...
Fetching 2025-02-28...
Fetching 2025-03-01...
Fetching 2025-03-02...
Fetching 2025-03-03...
Fetching 2025-03-04...
Fetching 2025-03-05...
Fetching 2025-03-06...
Fetching 2025-03-07...
Fetching 2025-03-08...
Fetching 2025-03-09...
Fetching 2025-03-10...
Fetching 2025-03-11...
Fetching 2025-03-12...
Fetching 2025-03-13...
Fetching 2025-03-14...
Fetching 2025-03-15...
Fetching 2025-03-16...
Fetching 2025-03-17...
Fetching 2025-03-18...
Fetching 2025-03-19...
Fetching 2025-03-20...
Fetching 2025-03-21...
Fetching 2025-03-22...
Fetching 2025-03-23...
Fetching 2025-03-24...
Fetching 2025-03-25...
Fetching 2025-03-26...
Fetching 2025-03-27...
Fetching 2025-03-28...
Fetching 2025-03-29...
Fetching 2025-03-30...
Fetching 2025-03-31...

In [16]:
df_all = pd.concat(all_data)
df_all.to_csv("/Users/kennethzhang/Desktop/VolAuction/data/es_futures_1m_all.csv")
print("Saved to es_futures_1m_all.csv")

Saved to es_futures_1m_all.csv

In [17]:
df_all

,Open,High,Low,Close,Volume,Dividends,Stock Splits,date
Datetime,,,,,,,,
2025-03-24 00:00:00-04:00,5754.00,5754.00,5752.75,5753.00,0,0.0,0.0,2025-03-24
2025-03-24 00:01:00-04:00,5753.00,5753.00,5752.75,5752.75,75,0.0,0.0,2025-03-24
2025-03-24 00:02:00-04:00,5753.00,5753.25,5752.75,5753.25,18,0.0,0.0,2025-03-24
2025-03-24 00:03:00-04:00,5753.00,5753.00,5752.50,5752.50,85,0.0,0.0,2025-03-24
2025-03-24 00:04:00-04:00,5752.50,5753.25,5752.50,5753.00,62,0.0,0.0,2025-03-24
...,...,...,...,...,...,...,...,...
2025-03-31 16:55:00-04:00,5645.75,5646.00,5645.00,5645.25,632,0.0,0.0,2025-03-31
2025-03-31 16:56:00-04:00,5645.25,5645.75,5644.25,5644.50,420,0.0,0.0,2025-03-31
2025-03-31 16:57:00-04:00,5644.50,5645.00,5644.00,5644.50,344,0.0,0.0,2025-03-31
2025-03-31 16:58:00-04:00,5644.50,5644.75,5644.00,5644.25,212,0.0,0.0,2025-03-31
2025-03-31 16:59:00-04:00,5644.00,5645.00,5644.00,5644.50,318,0.0,0.0,2025-03-31